name: magical_widget_generator
description: A Flutter package that helps to generate boilerplate codes in order to easily and magically manipulate the states of graphical user interface using streams and BLoCs. This package contains the actual source code generation logic.
version: 0.9.0
author: Raef Mousheimish <mch.raef@gmail.com>
homepage:

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  build: ^1.0.2
  source_gen: ^0.9.3
  rxdart: any
  magical_widget:
    path: ../magical_widget/

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_test: ^0.10.4
  build_runner: ^1.1.2

flutter:

